#!/bin/bash

# Fail on unset variables, command errors and pipe fail.
set -o nounset -o errexit -o pipefail

# Prevent commands misbehaving due to locale differences.
export LC_ALL=C LANG=C

SCRIPT_NAME="${0##*/}"

branch_name="$(git name-rev --name-only HEAD)"

if [ "_$branch_name" == '_master' ]; then
	echo "$SCRIPT_NAME: master branch is not branch to be commited" >&2
	exit 1
fi
